### ISSUE TITLE
Cloud Mqqt with homeassistant

### ISSUE THREAD

**Issue by platini76** [lucacalcaterra/risco-mqtt-bridge#1]
I don't understand how connect it.. I try several things...

my config:
HOMEASSISTANT
mqtt: 
  broker: ********* 
  port: *****  PORT WITHOUT SSL
  username: ****** USER CREATED IN USER&ACL PANEL WITH topic # and read/write
  password: ****

https://www.home-assistant.io/docs/mqtt/broker

same config for risco-mqtt-bridge (my riscocloud password are ok)

**Comment by platini76** [comment]
my config is ok... but no devices discover in homeassistant
which is my error?
I have to make other configurations?

**Comment by lucacalcaterra** [comment]
Ciao Sei italiano ? Scrivimi a Calcaterra. Luca@Gmail.com

Il giorno Sab 10 Nov 2018, 21:50 platini76 <notifications@github.com> ha
scritto:

**Comment by lucacalcaterra** [comment]
Fixed.. With last commit (so release 1.1) you can reflect states on MQTT for Home Assistant. See config example
