### ISSUE TITLE
Question: Exit delay

### ISSUE THREAD

**Issue by pergolafabio** [lucacalcaterra/risco-mqtt-bridge#10]
hey Luca, 

opened another question for this, in the other thread you mentioned that the exit timer is based on the app, and your code is using the the same timer

> This project act as the Risco app , so if you arm the connection via mqtt the panel, it arms instantly. This behaviour can be changed from risco panel config (if you have the installer code )

well, i am looking in the installer manual, see below, but i cant find a setting to setup the exit delay timer
only an exit delay timer for the risco original panels

so how can you setup the delay timer , so the same exit delay timers is running when using your bridge?

https://www.dropbox.com/s/3kmgl55brebxp7o/5IN1482_LightSYS_Installer_Manual.pdf?dl=0

**Comment by pergolafabio** [comment]
Hey , any feedback on this? I can't use it to arm my house, so can't use it as a replacement panel :(

**Comment by pergolafabio** [comment]
@lucacalcaterra 

maybe an idea:

can you put an variable in your script
like disarmtimer : 30

so if configured like 30 , if you arm/part arm the alarm, the command is send to riscocloud after the timer configured? i think this is only like a few line code?

thnx in advance

**Comment by lucacalcaterra** [comment]
Hi, it's possible to write in next release, quite simple 👍

**Comment by pergolafabio** [comment]
verry good :)

then i dont have to struggle with this in Home Assistant, since the mqtt platform there i verry limited

the manual_mqtt is platform in HA, there are more options , but that platform is not compatible with your script

**Comment by lucacalcaterra** [comment]
I configured the panel of an Italian friend on h.a. with mqtt and it worked, so I do not think there are problems with h.a.

**Comment by pergolafabio** [comment]
yes, i also have it working , but there are 2 platforms in Home Assistant
like i your readme
platform : mqtt => its working, but in HA the options are limited for codes and stuff
platform: manual_mqtt => not working, butr more controls

difference between the 2 is that on mqtt platform, all logic is in the alarm system itself, so it just sends the mqtt messages, like setup now
so therefore if we arm the panel from Home Assistant, its armed directly, unable to use then as an Panel on the wall :)
