### ISSUE TITLE
beta release

### ISSUE THREAD

**Issue by pergolafabio** [lucacalcaterra/risco-mqtt-bridge#14]
i pulled latest docker, but is it possible its not downloading the beta? only the 1.2 release?

**Comment by pergolafabio** [comment]
ok, updated my old config, the non-docker version with beta files
but if i start it with "node app.js" manually, i always have the same error that i cant connect to the MQTT server , not authorized
verry strange, the config.js file is exactly the same ... if i start 1.2 , no issues
the only difference i see in the config.js file, is that there are a lot of extra comma files ,,,,,,

**Comment by pergolafabio** [comment]
i needed to allow anonymous connections in my mqtt server , then it works
strange because in your config file, a user / pass was filed in, but seems its ignored

**Comment by pergolafabio** [comment]
anyway, tried running the beta , downloaded that zip, did an npm install again
so beta is running, but i dont see any discovery in Home Assistant? not seeing automaticly new devices

**Comment by lucacalcaterra** [comment]
Solved it ?

**Comment by pergolafabio** [comment]
Yes
