### ISSUE TITLE
seems it doesnt reconnect after disconnected..

### ISSUE THREAD

**Issue by pergolafabio** [lucacalcaterra/risco-mqtt-bridge#15]
hey @lucacalcaterra 

noticed lately that my state was not changing anymore, so turned on development
today i had the issue again, you see in log it was disconnected, it seems to reconnect, but it stopped polling?

log here ..

,05-04-2019 14:15:43 debug: return null, overview empty!
,05-04-2019 14:15:43 debug: Polled...counter:  5852
,05-04-2019 14:15:53 debug: polling ...
,05-04-2019 14:15:53 debug: return null, overview empty!
,05-04-2019 14:15:53 debug: Polled...counter:  5853
,05-04-2019 14:16:03 debug: polling ...
,05-04-2019 14:16:03 debug: return null, overview empty!
,05-04-2019 14:16:03 debug: Polled...counter:  5854
,05-04-2019 14:16:13 debug: polling ...
,05-04-2019 14:16:13 debug: return null, overview empty!
,05-04-2019 14:16:13 debug: Polled...counter:  5855
,05-04-2019 14:16:23 debug: polling ...
,05-04-2019 14:16:24 debug: return null, overview empty!
,05-04-2019 14:16:24 debug: Polled...counter:  5856
,05-04-2019 14:16:34 debug: polling ...
,05-04-2019 14:16:34 debug: return null, overview empty!
,05-04-2019 14:16:34 debug: Polled...counter:  5857
,05-04-2019 14:16:34 warn: Disconnected from cloud...relogin and init...
,05-04-2019 14:16:34 debug: Logged...Response code is 302: OK
,05-04-2019 14:16:35 debug: ...site and Pin Code sent...Response code is 302: OK
,05-04-2019 14:16:35 debug: ...Cameras taken...Response code is 200 and no data error: OK
,05-04-2019 14:16:36 debug: ...Event History taken...Response code is 200 and no data error: OK
,05-04-2019 14:16:36 debug: ...Detectors taken...Response code is 200 and no data error: OK
,05-04-2019 14:16:36 debug: ...Overview taken...Response code is 200 and no data error: OK
,05-04-2019 14:16:36 debug: return null, overview empty!
,05-04-2019 14:16:36 debug: newarmstatus emitted
,05-04-2019 14:16:36 info: Arming status: armed
,05-04-2019 14:16:36 info: publish messages on MQTT Server
,05-04-2019 14:16:36 debug: Init function for getting data from Cloud completed: OK
,05-04-2019 14:16:44 debug: polling ...

and then nothing, we are almost 2 hours later now

running in portainer

**Comment by rob1981forest** [comment]
Mine been running fine.....been messing with it today........all my lifx now flash red if the alarm goes off !!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
I never had issues with docker, seems to be happening since portainer... Strange, should be the same ... Seems it happens about 24 later or something

**Comment by rob1981forest** [comment]
Mine in portainer too.....looks fine......except time is an hour out on logs now clocks gone back in the UK but maybe it's getting that from portainer or my raspberry pi

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
I have no clue how to investigate this...
What have you done in portainer, only load image and set those volume bindings, that's all, not?

**Comment by rob1981forest** [comment]
Actually just looked again and I'm getting this 'return null, over view empty' message too now .

I was literally messing with this half and hour ago and all was fine

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
Ok, so yours is not polling either anymore? Can you make screenshots of your config?

**Comment by pergolafabio** [comment]
Also, do you have log files in your directory? Mine is always emtpy, I look in logs in portainer itself

**Comment by rob1981forest** [comment]
Just trying to look at then but now my HA seems to have reset to some old setup.......something wierd going on.

I had redirected logs from 2nd April......must be last time I restarted.

Combined.log shows all is well......it's portainer that is complaining.

Error.log is empty

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rob1981forest** [comment]
Actually that may have been my mistake on the HA gui.......my mqtt alarm panel on HA is still controlling the alarm fine

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
Ok, something else then... Can you make screenshots from your portainer, your settings?

**Comment by rob1981forest** [comment]
Will get you some later tonight hopefully......all I did was redirect the conf file and logs to a mount point on the pi which in turn is an NFS share on my Synology.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
Ok, thnx , restarted container, so all good for 24 hours, ok, looking forward to screenshot...

Do you have development node enabled? Normally you see logs then in the logs folder, but mine always stays empty

**Comment by rob1981forest** [comment]
Yes  , I've definitely had mine up and working over 24 hours.....

See attached photos.

No I don't have Dev mode enabled...... not really sure where that would be to be sure.


[Image]



[Image]




[Image]













Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
dont see the images :)

well, if i dont enable development as node, i dont see any logs coming in , its just blanc

**Comment by rob1981forest** [comment]
Sorry mate, will try again to get some actual screen shots and send over

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
np :)

but how do you check logs? i think my polling stopped already again ... just seems like its freeze

05-04-2019 17:27:37 debug: polling ...
,05-04-2019 17:27:37 debug: return null, overview empty!
,05-04-2019 17:27:37 debug: Polled...counter:  64
,05-04-2019 17:27:47 debug: polling ...
,05-04-2019 17:27:47 debug: return null, overview empty!
,05-04-2019 17:27:47 debug: Polled...counter:  65
,05-04-2019 17:27:57 debug: polling ...
,05-04-2019 17:27:57 debug: return null, overview empty!
,05-04-2019 17:27:57 debug: Polled...counter:  66
,05-04-2019 17:28:07 debug: polling ...
,05-04-2019 17:28:08 debug: return null, overview empty!
,05-04-2019 17:28:08 debug: Polled...counter:  67
,05-04-2019 17:28:18 debug: polling ...
,05-04-2019 17:28:18 debug: return null, overview empty!
,05-04-2019 17:28:18 debug: Polled...counter:  68
,05-04-2019 17:28:28 debug: polling ...
,05-04-2019 17:28:28 debug: return null, overview empty!
,05-04-2019 17:28:28 debug: Polled...counter:  69
,05-04-2019 17:28:38 debug: polling ...
,05-04-2019 17:28:38 debug: return null, overview empty!
,05-04-2019 17:28:38 debug: Polled...counter:  70
,05-04-2019 17:28:48 debug: polling ...
,05-04-2019 17:28:49 debug: return null, overview empty!
,05-04-2019 17:28:49 debug: Polled...counter:  71
,05-04-2019 17:28:59 debug: polling ...
,05-04-2019 17:28:59 debug: return null, overview empty!
,05-04-2019 17:28:59 debug: Polled...counter:  72
,05-04-2019 17:29:09 debug: polling ...
,05-04-2019 17:29:09 debug: return null, overview empty!
,05-04-2019 17:29:09 debug: Polled...counter:  73
,05-04-2019 17:29:19 debug: polling ...
,05-04-2019 17:29:19 debug: return null, overview empty!
,05-04-2019 17:29:19 debug: Polled...counter:  74
,05-04-2019 17:29:29 debug: polling ...
,05-04-2019 17:29:30 debug: return null, overview empty!
,05-04-2019 17:29:30 debug: Polled...counter:  75
,05-04-2019 17:29:40 debug: polling ...
,05-04-2019 17:29:40 debug: return null, overview empty!
,05-04-2019 17:29:40 debug: Polled...counter:  76
,05-04-2019 17:29:50 debug: polling ...
,05-04-2019 17:29:50 debug: return null, overview empty!
,05-04-2019 17:29:50 debug: Polled...counter:  77
,05-04-2019 17:30:00 debug: polling ...
,05-04-2019 17:30:00 debug: return null, overview empty!
,05-04-2019 17:30:00 debug: Polled...counter:  78
,05-04-2019 17:30:10 debug: polling ...
,05-04-2019 17:30:11 debug: return null, overview empty!
,05-04-2019 17:30:11 debug: Polled...counter:  79
,05-04-2019 17:30:21 debug: polling ...
,05-04-2019 17:30:21 debug: return null, overview empty!
,05-04-2019 17:30:21 debug: Polled...counter:  80
,05-04-2019 17:30:31 debug: polling ...
,05-04-2019 17:30:32 debug: return null, overview empty!
,05-04-2019 17:30:32 debug: Polled...counter:  81
,05-04-2019 17:30:42 debug: polling ...
,05-04-2019 17:30:42 debug: return null, overview empty!
,05-04-2019 17:30:42 debug: Polled...counter:  82
,05-04-2019 17:30:52 debug: polling ...
,05-04-2019 17:30:52 debug: return null, overview empty!
,05-04-2019 17:30:52 debug: Polled...counter:  83
,05-04-2019 17:31:02 debug: polling ...
,05-04-2019 17:31:03 debug: return null, overview empty!
,05-04-2019 17:31:03 debug: Polled...counter:  84
,05-04-2019 17:31:13 debug: polling ...
,05-04-2019 17:31:13 debug: return null, overview empty!
,05-04-2019 17:31:13 debug: Polled...counter:  85
,05-04-2019 17:31:23 debug: polling ...
,05-04-2019 17:31:23 debug: return null, overview empty!
,05-04-2019 17:31:23 debug: Polled...counter:  86
,05-04-2019 17:31:33 debug: polling ...
,05-04-2019 17:31:33 debug: return null, overview empty!
,05-04-2019 17:31:33 debug: Polled...counter:  87
,05-04-2019 17:31:43 debug: polling ...
,05-04-2019 17:31:44 debug: return null, overview empty!
,05-04-2019 17:31:44 debug: Polled...counter:  88
,05-04-2019 17:31:54 debug: polling ...
,05-04-2019 17:31:54 debug: return null, overview empty!
,05-04-2019 17:31:54 debug: Polled...counter:  89
,05-04-2019 17:32:04 debug: polling ...
,05-04-2019 17:32:04 debug: return null, overview empty!
,05-04-2019 17:32:04 debug: Polled...counter:  90
,05-04-2019 17:32:14 debug: polling ...
,05-04-2019 17:32:14 debug: return null, overview empty!
,05-04-2019 17:32:14 debug: Polled...counter:  91
,05-04-2019 17:32:24 debug: polling ...
,05-04-2019 17:32:25 debug: return null, overview empty!
,05-04-2019 17:32:25 debug: Polled...counter:  92
,05-04-2019 17:32:35 debug: polling ...
,05-04-2019 17:32:35 debug: return null, overview empty!
,05-04-2019 17:32:35 debug: Polled...counter:  93
,05-04-2019 17:32:45 debug: polling ...
,05-04-2019 17:32:45 debug: return null, overview empty!
,05-04-2019 17:32:45 debug: Polled...counter:  94
,05-04-2019 17:32:55 debug: polling ...
,05-04-2019 17:32:55 debug: return null, overview empty!
,05-04-2019 17:32:55 debug: Polled...counter:  95
,05-04-2019 17:33:05 debug: polling ...
,05-04-2019 17:33:06 debug: return null, overview empty!
,05-04-2019 17:33:06 debug: Polled...counter:  96
,05-04-2019 17:33:16 debug: polling ...
,
polling just stopped at 17.33 , dont see any new lines, its already 22.31 now

**Comment by rob1981forest** [comment]
My logs are redirected to an NFS share I mounted into the raspbian os my docker is on ..they seem to read fine there........

What hardware you running on ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
i am running an esxi server, with Hassos Hassio
i mounted like this : https://www.dropbox.com/s/6tflsu7rsyaq4ox/riscoportainer.JPG?dl=0
so the .js file is working fine, but my logs folder stays empty
you see also in screenshot that i enable development, then you see i think debug log

**Comment by rob1981forest** [comment]
[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
I don't see your images ;)

**Comment by pergolafabio** [comment]
@lucacalcaterra 

Can you help me out here, in my first reply you see it just stopped polling... But it's possible that my logs are maybe wrong... Seems portainer I think is not refreshing logs anymore after some time... Not 100% sure...

What I do know , is that after a while I don't receive information anymore, so need to restart the docker... Not sure why... So I want to capture logs, so created that volume binding, but the logs folder is always empty... Also if I enable development, to see debug...

Any idea why? 2 posts back you see a screenshot of my volume binding, it looks correct... I'd it maybe permission? Or do I need to create an empty log file ? I am stuck here

**Comment by pergolafabio** [comment]
happened again, this time after 2 days, i need to restart docker again 
state is again unavailable, also arm/disarm command dont do anything anymore

can some make me a screenshot how i can enable those logs? my logs folder is always empty

path in container i configured as :  /app/logs
also node_environment = development
thnx

**Comment by lucacalcaterra** [comment]
Hi Fabio, these days hav no time... can we sync next week ? Thanks, Luca

Il giorno mar 9 apr 2019 alle ore 22:29 pergolafabio <
notifications@github.com> ha scritto:

**Comment by pergolafabio** [comment]
Ok, np ;)

**Comment by rob1981forest** [comment]
this is mine...........
![Capture](https://user-images.githubusercontent.com/46425552/55877828-f2e5a580-5b92-11e9-9df4-36ab4f5ceec8.JPG)

**Comment by pergolafabio** [comment]
really dont get it, i have the exact same
you actually see log files on your host volume? 

this is  mine config, its the same

https://www.dropbox.com/s/pbxvkazf1o932ew/port.JPG?dl=0

**Comment by rob1981forest** [comment]
yeah, i get logs in mine - called combined.log

**Comment by pergolafabio** [comment]
maybe its a permission issue , but i dont know where to enter credentials in portainer

**Comment by pergolafabio** [comment]
no , its no permission issue, it can assess that folder, otherwise my config file wouldt load also
now tried docker on synology, also no combined.log file there if i start
i am missing something here

**Comment by pergolafabio** [comment]
ok, got it
i now first created that combined.log file, and did chmod 777 
now its populated, allthough i think if "development" is enabled, then it creates more files
@rob1981forest 

can you enable also development? like here
just add node
NODE_ENV => development
https://www.dropbox.com/s/pbxvkazf1o932ew/port.JPG?dl=0

**Comment by pergolafabio** [comment]
did now chmod 777 on logs folder

now it creates 2 files combined.log and error.log

but combined.log is not filling, the only text in it is like : 

10-04-2019 15:56:47 [32minfo[39m: Connected to MQTT Server
10-04-2019 15:56:52 [32minfo[39m: Arming status: armed
10-04-2019 15:56:52 [32minfo[39m: publish messages on MQTT Server

thats about it

**Comment by pergolafabio** [comment]
ok, seems its only populating "info" logs not "debug"
 i wait for @lucacalcaterra  how i can enable "debug" so i actually see "debug" in combined.log and error.log

i have set NODE_ENV to development
i see debug passing if i go to logs within the container in portainer itself, i just dont see them in the files

**Comment by pergolafabio** [comment]
ok, changed polling from 100000 to 150000 , didnt help either
i see it stopped polling again, issue/error in log , it just stops it seems

**Comment by rob1981forest** [comment]
Mine seems solid and hasn't let me down........your internet connectivity good ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
no internet issues here
stopped now portainer, and testing now docker on synology
never had issues there, will see in a few days

**Comment by Davewarrington** [comment]
Suffering the same situation here also, portainer in Ha, Log files seem ok, 24 hours later blank . one restart of the container and we're off again .

**Comment by pergolafabio** [comment]
ah, glad i am not the only one :) its not 24hours, sometimes sooner, sometimes longer i think, but indeed approx 1 day...
now stopped portainer, using docker on synology , rock solid for 3 days now
really dont understand issue with portainer :(

if we know how to enable/export debug logs, then we can start investigating, because i prefer to use portainer instaed of docker

**Comment by rob1981forest** [comment]
Very strange......my portainer seems fine......and I really have no idea what I'm doing so it's not like I have some expert configuration on there.......at least you have the answer

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Davewarrington** [comment]
The only thing i noticed of late was portainer received an update a few days ago ..

**Comment by pergolafabio** [comment]
yes, 0.6.0 , didnt try that one, i was an previous version
but shouldt not mather anyway

**Comment by Davewarrington** [comment]
Portainer disabled, issue still persists .. I'll have a look at the debug logs later on tonight if i can get to them :o

**Comment by pergolafabio** [comment]
So how are you running the container if disabled?

**Comment by Davewarrington** [comment]
Ahh only portainer was disabled,docker still running.

**Comment by pergolafabio** [comment]
ah ok , well in run the container now in docker "software on synology" , its now stable for 4 days
so it must be related in running the container under portainer/hassio
do you run hassio with portainer as addon?

**Comment by pergolafabio** [comment]
we need to know how we can enable debug log , so we can see when it quits polling and why

**Comment by rob1981forest** [comment]
I don't run Hassio.....I just have raspbian on a pi.....the docker and then portainer.....I then install the RPI home assistant image.

However my DS918+ turned up today so it's all gonna change soon !

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lucacalcaterra** [comment]
Have you solved it ?

**Comment by pergolafabio** [comment]
No, on portainer still issue, but on docker on Synology is stable...
How can I also enable debug log for export?

**Comment by pergolafabio** [comment]
ok, docker on synology was fine for a week
now back running it under portainer, let see what happens

@lucacalcaterra  , can you tell me how to enable debug log and export those to the files? so they are in combined.log and error.log  ?

thn

**Comment by pergolafabio** [comment]
today it happened on my docker (synology) as well, was stable for 3 days
had to restart it
now enabled debug on it

**Comment by lucacalcaterra** [comment]
Set node on development mode... google for it

Il giorno gio 25 apr 2019 alle ore 21:43 pergolafabio <
notifications@github.com> ha scritto:

**Comment by pergolafabio** [comment]
yes, i have done it now
but is it also possible to export those debug logs to your export log files?
if i enable debug, only the "info" messages are still in export files

**Comment by Davewarrington** [comment]
Any update on this ? ... or thoughts :D

**Comment by lucacalcaterra** [comment]
According to this line (https://github.com/lucacalcaterra/risco-mqtt-bridge/blob/769ec6714a7ed5fca64783fdaabab5d2dfcf4837/logger.js#L35) logs must be at debug level if node environment is set to development

So... have you set node environment into container (and not on host ) ?

**Comment by pergolafabio** [comment]
hi @lucacalcaterra 
if i enable indeed debug, i see in portailer logs, more detailed stuff , but the logfiles for export, dont contain those debug logs, so i still dont know how to investigate the issue

**Comment by Davewarrington** [comment]
Anybody making any head way on this issue ? My logs wont even write out to the log folder, but im assuming it's permissions related :(

**Comment by lucacalcaterra** [comment]
> hi @lucacalcaterra
> if i enable indeed debug, i see in portailer logs, more detailed stuff , but the logfiles for export, dont contain those debug logs, so i still dont know how to investigate the issue

Have you sh into container ? There is the logs folder there ?

**Comment by Davewarrington** [comment]
Had to change perms on logs folders, waiting for the issue to reoccur now ..

**Comment by Davewarrington** [comment]
Reviewing the logs here, I see the following "Exception on arm/disarm command: TypeError: Cannot read property 'text' of undefined" and after this point it fails to poll again the web interface..

**Comment by pergolafabio** [comment]
seems since yesterday, polling was down, but i also noticed i cant login anymore with the app itself
anyelse also issues?

also on website itself , i get incorrect pin;, while its correct

**Comment by Davewarrington** [comment]
No issues here with logon .

**Comment by pergolafabio** [comment]
And you are also using this application too with polling? I maybe thought Risco blocked me because to many polling requests on their site

**Comment by rob1981forest** [comment]
Yeah no issues forme either

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rob1981forest** [comment]
I don't know if I'm using polling......I've not messed with anything so if it comes as default for polling then yes I am

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
Strange, well I stopped this container, maybe I am locked or something, and it will fix itself after a few hours

**Comment by pergolafabio** [comment]
well, this docker is not working for either anymore, it doesnt login  anymore, so clearly something wrong with my site ....

```
2019-07-07 10:05:19,stdout,07-07-2019 12:05:19 [34mdebug[39m: Init function for getting data from Cloud completed: OK

2019-07-07 10:05:19,stdout,07-07-2019 12:05:19 [34mdebug[39m: no new status

2019-07-07 10:05:19,stdout,07-07-2019 12:05:19 [34mdebug[39m: newarmstatus emitted

2019-07-07 10:05:19,stdout,"07-07-2019 12:05:19 [34mdebug[39m: return null, overview empty!
"
2019-07-07 10:05:19,stdout,07-07-2019 12:05:19 [34mdebug[39m: Logged...Response code is 302: OK

2019-07-07 10:05:18,stdout,07-07-2019 12:05:18 [33mwarn[39m: Disconnected from cloud...relogin and init...

2019-07-07 10:05:18,stdout,07-07-2019 12:05:18 [34mdebug[39m: Polled...counter:  7

2019-07-07 10:05:18,stdout,"07-07-2019 12:05:18 [34mdebug[39m: return null, overview empty!
"
2019-07-07 10:05:18,stdout,07-07-2019 12:05:18 [34mdebug[39m: polling ...

2019-07-07 10:05:10,stdout,07-07-2019 12:05:10 [34mdebug[39m: Init function for getting data from Cloud completed: OK

2019-07-07 10:05:10,stdout,07-07-2019 12:05:10 [34mdebug[39m: no new status

2019-07-07 10:05:10,stdout,07-07-2019 12:05:10 [34mdebug[39m: newarmstatus emitted

2019-07-07 10:05:10,stdout,"07-07-2019 12:05:10 [34mdebug[39m: return null, overview empty!
"
2019-07-07 10:05:09,stdout,07-07-2019 12:05:09 [34mdebug[39m: Logged...Response code is 302: OK

2019-07-07 10:05:08,stdout,07-07-2019 12:05:08 [33mwarn[39m: Disconnected from cloud...relogin and init...
```

**Comment by pergolafabio** [comment]
my issue is resolved with the codes, verry strange, i have 3 users on my risco system
all 3 PIN codes gave incorrect error, when working with app/riscocloud
but 3 pin codes were still working on the panel itself...

so i overwrited the 3 pin codes again, gave it the same number and afterwards app / riscocloud was working again... verry strange

maybe risco is blocking us now? because of maybe the pollings? maybe they are locking the site id or something?

**Comment by rob1981forest** [comment]
I really hope they don't block us......this is so very useful......if I made my purchase again it would not be risco.......they need share and offer more API support

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Davewarrington** [comment]
A quick update on this, as it's been really annoying me of late :D .

IF you load HA-Dockermon and set up a switch to start and stop the container every 15 mins it should provide decent coverage to ensure like me, you wont arrive home, and have to restart the container in order to get it polling again .. 

It's a hacky fix :( but it'll buy some time ..

**Comment by pergolafabio** [comment]
you mean error below? i also have that somtimes, but mine just stays polling

but i switched back to portainer now, it was running quite stable with docker on synology
now testing portainer again, it had some updates

08-07-2019 21:00:56 [31merror[39m: Exception getting Control Panel State: TypeError: Cannot read property 'partInfo' of undefined

**Comment by Davewarrington** [comment]
Yup that's the error alright. Restarting the container is far from efficient, but, i'll try and come up with a better way to spot this issue, I do find that you dont always catch it via  "39m: Exception getting Control Panel State: TypeError: Cannot read property 'partInfo' of undefined"

**Comment by rob1981forest** [comment]
Updated my Synology last night so had to down it all and my docker container for this had been up without issue for 39 days.......strange how people are getting differ results here

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lucacalcaterra** [comment]
No issues on my docker server running on an Asus Tinkerboard... i manage it from Portainer...

**Comment by pergolafabio** [comment]
well, on docker (synology) also stable
now switched back to portainer (stable for 2 days)
that error below, i also get it from time to time, but in my case it just stays polling

the only issues i had were:

1) portainer => after a few days, not connected anymore, so needed to restart container ( no logs yet, thats why i am testing portainer again...
2) all my PIN codes were suddenly incorrect when i tried APP/RISCOCLOUD, pin codes were still correct on my local panels, verry strange, so with risco configuration sotware, i just overwrited the pins, and all was ok afterwards

anyway, are you still working on a python version? would love to see it as a component in HA
i prefer a component instead of an addon, a component is much easier to integrate

**Comment by pergolafabio** [comment]
oh, and btw, risco launched a new module to integrate with knx/modbus... first step to domotica :)
i dont think its an advantage for us anyway

https://www.riscogroup.com/uk/products/product/52958

**Comment by memone75** [comment]
I also have the problem of the daemon stopping polling. I kinda of solved it using the systemd watchdog. Here is a bit of documentation:

https://www.npmjs.com/package/sd-notify

It's a workaround, but so far it seems to do the job.
Hope this helps someone.

**Comment by pergolafabio** [comment]
Can you share some details how to setup?

**Comment by memone75** [comment]
I installed the sd-notify package as per previous link. Then I enabled the systemd watchdog adding the line "WatchdogSec=" with a value that should be at least twice the mqtt bridge polling time. I've set it to 120, so if the bridge is stuck for 2 minutes, it gets restarted.

This is my risco.service file in /etc/systemd/system/

```
[Unit]
Description=Risco Node.js App
After=network.target mosquitto.service

[Service]
Type=simple
User=pi
ExecStart=/usr/bin/node /yourpathto/app.js
Restart=always
TimeoutStartSec=30
WatchdogSec=120

[Install]
WantedBy=multi-user.target

```

in the file app.js I just added this line on top

`
const notify = require('sd-notify')
`

and added the watchdog notify call here:

```
 riscoPoller.on('polled', () => {
    riscoLogger.log('debug', `Polled...counter:  ${riscoPoller.counter}`);
    notify.watchdog();
    riscoLogger.log('debug', `Watchdog notified`);
  });
```

I didn't have the time to debug anything, so I just have the daemon killed and restarted if it stops to log. Dirty hack, but so far it seems to work.

**Comment by pergolafabio** [comment]
Ok, thnx for sharing, som stuff to read

**Comment by pergolafabio** [comment]
can this also be implemented in the docker?
