### ISSUE TITLE
HomeAssistant addon

### ISSUE THREAD

**Issue by daxda** [lucacalcaterra/risco-mqtt-bridge#16]
hi luca, I tried to add your repo directly to homeass as an addon, but there is a ptobkrma in the repository structure if you could modify it as indicated in the homeass documentation, your app would become very easy to integrate
https://developers.home-assistant.io/docs/en/hassio_addon_config.html

**Comment by pergolafabio** [comment]
Really interested to see this as add-on, or even coded in .py ;)

**Comment by pollinolas** [comment]
Waiting for a hassio add-on for this,please

**Comment by lucacalcaterra** [comment]
Must rewrite it with Python... I must learn it :-( I'll need find time to adapt it... Probably i'll do it

**Comment by pollinolas** [comment]
thanks for all your work and take your time

**Comment by pollinolas** [comment]
> Debo reescribirlo con Python ... Debo aprenderlo :-( Necesito encontrar tiempo para adaptarlo ... Probablemente lo haré


Hello, sorry for the inconvenience, you have had time to start with the addon for hass.io?, I am unable to install it by docker and I am waiting for someone to add this as an addon, a greeting and thanks

**Comment by lucacalcaterra** [comment]
Some days ago i start to study how create ... but without not so much successful :-( I wrote only a little app in python and don't know it very well... Anyone can give me a point of start ?

**Comment by pollinolas** [comment]
Hope someone can help you, i have not knowledge about it

**Comment by pollinolas** [comment]
I am willing to pay for someone to help me install this component in hass.io,someone can help me?

**Comment by lucacalcaterra** [comment]
Hi, i'll start to develop it in one month or two

**Comment by pergolafabio** [comment]
good to hear
i still have issues with loosing connection if i run your docker in portainer
if i run it on "docker" from synology, its stable

**Comment by lucacalcaterra** [comment]
@Fabio Pergola <pergola.fabio@gmail.com> Portainer it's only a container
manager (GUI), i use my app on an asus tinker with docker installed and
have no issues... portainer should not be the problem...



Il giorno ven 14 giu 2019 alle ore 09:47 pergolafabio <
notifications@github.com> ha scritto:

**Comment by pergolafabio** [comment]
yeah i know, but i have only issues when i run your container in portainer, not in docker,
i dont know why , it just like it stops polling after a while
i have logging enabled to a logs folder, and set the environment to "development" , but i dont see any debug logs in  the combined.log or the error.log files, just the regular info

**Comment by pollinolas** [comment]
> Hi, i'll start to develop it in one month or two

hi,i cant wait to see and enjoy it.thanks very much

**Comment by pergolafabio** [comment]
ok, i have found another githib project, this is addon for hassio
@lucacalcaterra  , maybe no need to convert yours now? since its already excist
seems he is using an API? 

https://github.com/martingrayson/hassio-addons/tree/master/risco-hass-bridge
https://github.com/martingrayson/risco-hass-bridge

**Comment by lucacalcaterra** [comment]
Don't know the HASS architecture. These projects (i suppose) are thinked for HASS architecture...

This bridge , instead, it's thinked for working with any kind of domotic controller via MQTT.
