### ISSUE TITLE
running on Docker within Synology

### ISSUE THREAD

**Issue by rob1981forest** [lucacalcaterra/risco-mqtt-bridge#17]
Hi, ive had this running on my Pi with docker for some time now and all is well but just bought a new synology 918+ so want to move it to docker on there- Home Assistant installs and runs ok but cant get the Risco bridge going.

Anyone got any experience here ?

Logs suggest a permission issue but not sure how to resolve:

Error: EACCES: permission denied, open '/app/config/config.js'

Thanks in advance
Rob

**Comment by rob1981forest** [comment]
seems ive just fixed it !

you need to redirect the logs and node.js to within the 'docker' folder that is auto created on the synology when docker is installed

**Comment by lucacalcaterra** [comment]
Can close it ?

**Comment by rob1981forest** [comment]
Yes, thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
