### ISSUE TITLE
Trigger panic alarm

### ISSUE THREAD

**Issue by rob1981forest** [lucacalcaterra/risco-mqtt-bridge#19]
I don't think this is possible but is there anyway we can trigger a panic alarm from home assistant so say for example I see someone outside my house on a camera I can just press a button and the alarm goes off ?

I have a panic button that does this so essentially I would just need to trigger that detector...

Could it be possible ?

**Comment by pergolafabio** [comment]
not sure if you can trigger a panic alarm, i believe only on the panel itself
maybe if you want to activate the siren, i believe its connected to an output
with an sms code, you can activate that output, so your sirene goes off :)

see here : https://www.dropbox.com/s/s5sf8wydbgk7hd2/sms%20codes.pdf?dl=0

not tried it myself

**Comment by rob1981forest** [comment]
Ok thanks, yeah didn't think I would be able to do it the way I wanted....... thanks for the pdf

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
