### ISSUE TITLE
Time zone ?

### ISSUE THREAD

**Issue by Davewarrington** [lucacalcaterra/risco-mqtt-bridge#20]
I've only really noticed this of late, but the  Time zone seems to be hard coded to Europe/Rome ? but my time on the docker container is  GMT -1 

I've Tried an ENV or TZ=Europe/Dublin but no joy...

**Comment by lucacalcaterra** [comment]
No time to investigate  now . i'll check asap.

**Comment by lucacalcaterra** [comment]
> I've only really noticed this of late, but the Time zone seems to be hard coded to Europe/Rome ? but my time on the docker container is GMT -1
> 
> I've Tried an ENV or TZ=Europe/Dublin but no joy...
Timezone it's not hard coded..

Probably TimeZone can be changed from your Risco user profile ?
Or playing with Docker config .

**Comment by lucacalcaterra** [comment]
> I've only really noticed this of late, but the Time zone seems to be hard coded to Europe/Rome ? but my time on the docker container is GMT -1
> 
> I've Tried an ENV or TZ=Europe/Dublin but no joy...

I'm rebuilding an arm image on docker of this project... You've the reason, TZ it's hard coded. In next releases i'll try to provide a method for change it.

**Comment by Davewarrington** [comment]
Thanks Luca :D i pulled the latest release but havent looked if i can set it as an env yet .
