### ISSUE TITLE
My pin code not working anymore... probably Risco lock me ?

### ISSUE THREAD

**Issue by lucacalcaterra** [lucacalcaterra/risco-mqtt-bridge#23]
Hi there,

from this morning my pin code of my site not working anymore... Now i can't access nor app nor web risco cloud. Probably Risco lockout my user on the cloud ?

Have you the same issues ?

**Comment by pergolafabio** [comment]
Yeah , had the same issue, all pincodes we're locked, only on panel they did work... So I overwrited them again, and then cloud/app was working again

**Comment by Davewarrington** [comment]
I noticed over the weekend the app updated, I can lock / unlock via finger print now, but more importantly,  If i use the same account on the bridge + the app, it complains the same account cannot be logged in at the same time ...

**Comment by pergolafabio** [comment]
Indeed , fingerprint is a nice add-on, about same z count , that was also before , just try again in a few seconds

**Comment by lucacalcaterra** [comment]
> Yeah , had the same issue, all pincodes we're locked, only on panel they did work... So I overwrited them again, and then cloud/app was working again

This is the fix. Thanks.
