### ISSUE TITLE
Disconnected from cloud...relogin and init...

### ISSUE THREAD

**Issue by mancioshell** [lucacalcaterra/risco-mqtt-bridge#25]
Hi,
thank you for your project.

I have cloned master branch of your github project. I have installed all npm dependencies, and i have started the app.

My username, password, pin and SelectedSiteId are correct, but application give me this error, and enter in an infinite loop:

07-09-2019 09:43:47 debug: Class Connection Constructor end
07-09-2019 09:43:48 info: Connected to MQTT Server
07-09-2019 09:43:48 debug: Logged...Response code is 302: OK
07-09-2019 09:43:49 debug: ...site and Pin Code sent...Response code is 302: OK
07-09-2019 09:43:50 debug: return null, overview empty!
07-09-2019 09:43:50 debug: newarmstatus emitted
07-09-2019 09:43:50 debug: no new status
07-09-2019 09:43:50 debug: Init function for getting data from Cloud completed: OK
07-09-2019 09:43:50 debug: polling started...
07-09-2019 09:44:00 debug: polling ...
07-09-2019 09:44:00 debug: return null, overview empty!
07-09-2019 09:44:00 debug: Polled...counter:  0
07-09-2019 09:44:00 warn: Disconnected from cloud...relogin and init...

I already tested this project before now in another raspberry (with home assistant) installation, and i never have got this type of error.
Maybe, has been there any change in the cloud?

**Comment by lucacalcaterra** [comment]
Hi !

Some days ago I've updated the  mom's dependencies but I noticed that
something break all things... probably the axios library.

Later in the morning  I'll check and update . I'll send you a msg to notify

Luca

Il Sab 7 Set 2019, 10:55 - <notifications@github.com> ha scritto:

**Comment by mancioshell** [comment]
Yes the issue disappeared if i use axios@0.18.0 instead of 0.19.0.

Thank you!

**Comment by lucacalcaterra** [comment]
Yes ... that's problem.

I've fixed version master branch.

Thanks !

Il giorno sab 7 set 2019 alle ore 15:24 - <notifications@github.com> ha
scritto:
