### ISSUE TITLE
error: Exception getting Overview: Error: getaddrinfo EAI_AGAIN www.riscocloud.com:443

### ISSUE THREAD

**Issue by daxda** [lucacalcaterra/risco-mqtt-bridge#27]
since yesterday i have this error, have an idea what it depends on?
error: Exception getting Overview: Error: getaddrinfo EAI_AGAIN www.riscocloud.com:443

**Comment by ekkesa** [comment]
Got this error too - Started some time during the day yesterday.

UPDATE: I specified DNS servers for the container, and so far it seems to have helped.

**Comment by pergolafabio** [comment]
maybe it was an issue on risco site

**Comment by ekkesa** [comment]
I was able to log into the cloud via a browser from the same network. The issue haven't popped up again, so it seems some strange docker dns issue.
