### ISSUE TITLE
No overview

### ISSUE THREAD

**Issue by KennieNL** [lucacalcaterra/risco-mqtt-bridge#3]
Hi,

I'm trying to get this to work with my alarm system.
I've got the correct Site ID from the HTML source and used it in the config.
After running the app it will show me 'return null, overview empty'.

I do see my sensors, events etc. on the riscocloud page.

Log:
> 18-11-2018 17:40:40 debug: Class Connection Constructor end
> 18-11-2018 17:40:40 info: Connected to MQTT Server
> 18-11-2018 17:40:40 debug: Logged...Response code is 302: OK
> 18-11-2018 17:40:41 debug: ...site and Pin Code sent...Response code is 302: OK
> 18-11-2018 17:40:41 debug: ...Cameras taken...Response code is 200 and no data error: OK
> 18-11-2018 17:40:41 debug: ...Event History taken...Response code is 200 and no data error: OK
> 18-11-2018 17:40:41 debug: ...Detectors taken...Response code is 200 and no data error: OK
> 18-11-2018 17:40:41 debug: ...Overview taken...Response code is 200 and no data error: OK
> 18-11-2018 17:40:42 debug: return null, overview empty!
> 18-11-2018 17:40:42 debug: newarmstatus emitted
> 18-11-2018 17:40:42 debug: no new status
> 18-11-2018 17:40:42 debug: Init function for getting data from Cloud completed: OK
> 18-11-2018 17:40:42 debug: polling started...
> 18-11-2018 17:40:52 debug: polling ...
> 18-11-2018 17:40:52 debug: return null, overview empty!
> 18-11-2018 17:40:52 debug: Polled...counter:  0
> 18-11-2018 17:41:02 debug: polling ...
> 18-11-2018 17:41:02 debug: return null, overview empty!
> 18-11-2018 17:41:02 debug: Polled...counter:  1
> 18-11-2018 17:41:12 debug: polling ...
> 18-11-2018 17:41:12 debug: return null, overview empty!

I would expect to see all my sensors in MQTT right?

Any way we can debug this easily?

Regards,
Kenneth

**Comment by lucacalcaterra** [comment]
It's a normal behavior. 

App poll continously the cloud , checking for new status.

While app running try to open your app on mobile and , i.e., change the arming status... Now you must see new status arrived..

In your mqtt, have messages on topics ?

> Hi,
> 
> I'm trying to get this to work with my alarm system.
> I've got the correct Site ID from the HTML source and used it in the config.
> After running the app it will show me 'return null, overview empty'.
> 
> I do see my sensors, events etc. on the riscocloud page.
> 
> Log:
> 
> > 18-11-2018 17:40:40 debug: Class Connection Constructor end
> > 18-11-2018 17:40:40 info: Connected to MQTT Server
> > 18-11-2018 17:40:40 debug: Logged...Response code is 302: OK
> > 18-11-2018 17:40:41 debug: ...site and Pin Code sent...Response code is 302: OK
> > 18-11-2018 17:40:41 debug: ...Cameras taken...Response code is 200 and no data error: OK
> > 18-11-2018 17:40:41 debug: ...Event History taken...Response code is 200 and no data error: OK
> > 18-11-2018 17:40:41 debug: ...Detectors taken...Response code is 200 and no data error: OK
> > 18-11-2018 17:40:41 debug: ...Overview taken...Response code is 200 and no data error: OK
> > 18-11-2018 17:40:42 debug: return null, overview empty!
> > 18-11-2018 17:40:42 debug: newarmstatus emitted
> > 18-11-2018 17:40:42 debug: no new status
> > 18-11-2018 17:40:42 debug: Init function for getting data from Cloud completed: OK
> > 18-11-2018 17:40:42 debug: polling started...
> > 18-11-2018 17:40:52 debug: polling ...
> > 18-11-2018 17:40:52 debug: return null, overview empty!
> > 18-11-2018 17:40:52 debug: Polled...counter:  0
> > 18-11-2018 17:41:02 debug: polling ...
> > 18-11-2018 17:41:02 debug: return null, overview empty!
> > 18-11-2018 17:41:02 debug: Polled...counter:  1
> > 18-11-2018 17:41:12 debug: polling ...
> > 18-11-2018 17:41:12 debug: return null, overview empty!
> 
> I would expect to see all my sensors in MQTT right?
> 
> Any way we can debug this easily?
> 
> Regards,
> Kenneth

**Comment by KennieNL** [comment]
In MQTT I see totally nothing, I'm even subscribing to '#' so I should be able see all msgs.
I do run mosquitto as MQTT server

When arming and is darming the panel in the log:
> 20-11-2018 12:51:27 debug: polling ...
> 20-11-2018 12:51:28 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:51:28 debug: Polled...counter:  39
> 20-11-2018 12:51:28 debug: newarmstatus emitted
> 20-11-2018 12:51:28 debug: no new status
> 20-11-2018 12:51:28 info: Status panel infos arrived
> 20-11-2018 12:51:38 debug: polling ...
> 20-11-2018 12:51:38 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:51:38 debug: Polled...counter:  40
> 20-11-2018 12:51:38 debug: newarmstatus emitted
> 20-11-2018 12:51:38 debug: no new status
> 20-11-2018 12:51:38 info: Status panel infos arrived
> 20-11-2018 12:51:48 debug: polling ...
> 20-11-2018 12:51:49 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:51:49 debug: Polled...counter:  41
> 20-11-2018 12:51:49 debug: newarmstatus emitted
> 20-11-2018 12:51:49 debug: no new status
> 20-11-2018 12:51:49 info: Status panel infos arrived
> 20-11-2018 12:51:59 debug: polling ...
> 20-11-2018 12:52:00 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:52:00 debug: Polled...counter:  42
> 20-11-2018 12:52:00 debug: newarmstatus emitted
> 20-11-2018 12:52:00 debug: no new status
> 20-11-2018 12:52:00 info: Status panel infos arrived
> 20-11-2018 12:52:10 debug: polling ...
> 20-11-2018 12:52:10 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:52:10 debug: Polled...counter:  43
> 20-11-2018 12:52:10 debug: newarmstatus emitted
> 20-11-2018 12:52:10 debug: no new status
> 20-11-2018 12:52:10 info: Status panel infos arrived
> 20-11-2018 12:52:20 debug: polling ...
> 20-11-2018 12:52:20 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:52:20 debug: Polled...counter:  44
> 20-11-2018 12:52:20 debug: newarmstatus emitted
> 20-11-2018 12:52:20 debug: no new status
> 20-11-2018 12:52:20 info: Status panel infos arrived
> 20-11-2018 12:52:30 debug: polling ...
> 20-11-2018 12:52:31 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:52:31 debug: Polled...counter:  45
> 20-11-2018 12:52:31 debug: newarmstatus emitted
> 20-11-2018 12:52:31 debug: no new status
> 20-11-2018 12:52:31 info: Status panel infos arrived
> 20-11-2018 12:52:41 debug: polling ...
> 20-11-2018 12:52:41 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:52:41 debug: Polled...counter:  46
> 20-11-2018 12:52:41 debug: newarmstatus emitted
> 20-11-2018 12:52:41 debug: no new status
> 20-11-2018 12:52:41 info: Status panel infos arrived
> 20-11-2018 12:52:51 debug: polling ...
> 20-11-2018 12:52:52 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:52:52 debug: Polled...counter:  47
> 20-11-2018 12:52:52 debug: newarmstatus emitted
> 20-11-2018 12:52:52 debug: no new status
> 20-11-2018 12:52:52 info: Status panel infos arrived
> 20-11-2018 12:53:02 debug: polling ...
> 20-11-2018 12:53:03 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:53:03 debug: Polled...counter:  48
> 20-11-2018 12:53:03 debug: newarmstatus emitted
> 20-11-2018 12:53:03 debug: no new status
> 20-11-2018 12:53:03 info: Status panel infos arrived
> 20-11-2018 12:53:13 debug: polling ...
> 20-11-2018 12:53:14 debug: ...Control Panel State taken and overview not empty... OK
> 20-11-2018 12:53:14 debug: Polled...counter:  49
> 20-11-2018 12:53:14 debug: newarmstatus emitted
> 20-11-2018 12:53:14 debug: no new status
> 20-11-2018 12:53:14 info: Status panel infos arrived

**Comment by lucacalcaterra** [comment]
What panel do you have ? MyElas or Risco ?

Can you send me your logs and config.js (without your credentials, obviously) ?

**Comment by KennieNL** [comment]
MyELAS (Electronics Line)

Sure, any specifics parts? or all? the ones above should already be it, I dont see any other data
config.js only exports.Conn.loginData array and exports.Mqtt.options.username and password been modified.

Thanks :)

**Comment by lucacalcaterra** [comment]
All...

**Comment by kkmaslowski** [comment]
@KennieNL: check maybe you made the same mistake as I. I subscribed with mosquitto_sub to '/#', not to 'riscopanel/#'.

**Comment by KennieNL** [comment]
Sorry for delay.
Yes I'm subscribed to '#', but changing it to '/#' doesn't help either. I do see updates from other devices on my MQTT server.

Attachted the console output and combined log, I can't do the error one since it's empty. I've run the program, armed and disarmed the panel.

[console.txt](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2632631/console.txt)
[combined.log](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2632632/combined.log)

**Comment by lucacalcaterra** [comment]
Sorry guys, at this time have no time to spend on it... as soon as
possibile i'll fix if there are issues...

Cheers!

Il giorno ven 30 nov 2018 alle ore 10:04 KennieNL <notifications@github.com>
ha scritto:

**Comment by KennieNL** [comment]
I do think the problem is within getArmStatus
My partInfo looks like: partInfo: { armedStr: 'No ', disarmedStr: 'Yes ', partarmedStr: 'No '}

So the partInfo.armedStr[0] > 0 etc. doesn't get triggered. I added a else for debug and this gets triggered. I wonder how partInfo looks for others?

**Comment by SimonThoustrup** [comment]
I see the same in partInfo (for an iConnect2 panel (MyELAS)):
 ...PartInfo contains armedStr: No ; disarmedStr: Yes ; partarmedStr: No ;
Disarm works via MQTT but nothing else.

Replacing getArmStatus in serverHandler.js with the following makes the right panel status appear on MQTT.

  getArmStatus(partInfo) {
    if (partInfo['armedStr'] == 'Yes ') this.riscoArmStatus = Config.States.armStatus.ARMED;
    else if (partInfo['disarmedStr'] == 'Yes ') this.riscoArmStatus = Config.States.armStatus.DISARMED;
    else if (partInfo['partarmedStr'] == 'Yes ' ) this.riscoArmStatus = Config.States.armStatus.PARTARMED;
    }
    if (this.OngoingAlarm) this.riscoArmStatus = Config.States.armStatus.ONALARM;
    return this.riscoArmStatus;
  }

Replacing armCommands in config.js with:

 armCommands: {
    ARM: 'ELArm1',
    DISARM: 'disarmed',
    PARTARM: 'ELArm4',
  },

and configuring HA accordingly:

alarm_control_panel:
  - platform: mqtt
    state_topic: "riscopanel/armstatus"
    command_topic: "riscopanel/armstatus/SET"
    payload_disarm: "disarmed"
    payload_arm_home: "ELArm4"
    payload_arm_away: "ELArm1"

makes both disarm, perimeter arm and full arm work like a charm.

**Comment by KennieNL** [comment]
That looks like there is a difference between MyELAS and Risco...
Have you also tested for perimeter arming by any chance?

When I look in the HTML source it looks like ELArm4 is perimeter:

>                    <div class="row part">
>                         <label>Partial </label>
>                         <div class="frame">
>                             <span class="check-area partially" data-cmd="2">
>                                 <input type="radio" name="ELArm">
>                             </span>
>                         </div>
>                     </div>
>                     <div class="row part">
>                         <label>Perimeter </label>
>                         <div class="frame">
>                             <span class="check-area partially" data-cmd="4">
>                                 <input type="radio" name="ELArm">
>                             </span>
>                         </div>
>                     </div>
>                     <div class="row part">
>                         <label>Part.+Perim. </label>
>                         <div class="frame">
>                             <span class="check-area partially" data-cmd="6">
>                                 <input type="radio" name="ELArm">
>                             </span>
>                         </div>
>                     </div>
>                     <div class="row full">
>                         <label>Full </label>
>                         <div class="frame">
>                             <span class="check-area armed" data-cmd="1">
>                                 <input type="radio" name="ELArm">
>                             </span>
>                         </div>
>                     </div>

**Comment by SimonThoustrup** [comment]
Yes, full and perimeter is what I have configured. I don't have any partial arm set up, so I cannot test those. But I believe it would be ELArm2 and ELArm6 as indicated in the code quoted by you.

**Comment by lucacalcaterra** [comment]
I must have the response of API request... In this way cannot do so many tests.

Although I understand security issues, I can only work if someone provides me with an account to work on his panel :-(


let me know if there is any volunteer .

Bye !
