### ISSUE TITLE
how to change the system pin class request

### ISSUE THREAD

**Issue by annu09** [lucacalcaterra/risco-mqtt-bridge#32]
i need to change the system pin class from sitepin to key because my security company uses Risco software/control panel but on their own servers with the 2014 version of riscocloud and there the system pin HTML class is key

**Comment by annu09** [comment]
> i need to change the system pin class from sitepin to key because my security company uses Risco software/control panel but on their own servers with the 2014 version of riscocloud and there the system pin HTML class is key

I am using the docker version on unraid btw.

**Comment by lucacalcaterra** [comment]
Close for inactivity
