### ISSUE TITLE
Question: Can HA detect when alarm is in process of been set?

### ISSUE THREAD

**Issue by DrJohnT** [lucacalcaterra/risco-mqtt-bridge#33]
Is it possible for HA to detect when alarm is in process of been set?
What I mean is when I leave the house, there is approx 40 seconds when the alarm is in a preset mode and the panel is beeping - basically giving me time to exit the flat.

What I would like to do is have HA alert me that a window has been left open during this 40 seconds.  Having it alert me afterwards would be rather frustrating as I would have to unlock the door as well as unset the alarm.

**Comment by pergolafabio** [comment]
there are configurable pending times
or set somekind of boolean with a timer to true

**Comment by DrJohnT** [comment]
Not sure what you mean by "configurable pending times".  

What I am really asking, in that 40 seconds will the state_topic: "riscopanel/armstatus" return some other status like "setting".  Or is there some other MQTT message I could intercept to get the "setting" status?

**Comment by pergolafabio** [comment]
That's also a road, intercept the mqtt , create a new one that fires a script with a delay and new mqtt arm message
