### ISSUE TITLE
Unable to set the alarm

### ISSUE THREAD

**Issue by karlismaj** [lucacalcaterra/risco-mqtt-bridge#35]
Hello
I have following shown in the log. Were is the problem?

![image](https://user-images.githubusercontent.com/32447346/93005633-77dca780-f55b-11ea-8b48-1d94913a169a.png)

Other issue is that i'm getting error Failed to call service alarm_control_panel/alarm_arm_away. must contain at least one entity_id, area_id

Thank you very much

**Comment by lucacalcaterra** [comment]
Never  worked before  or before worked  and now  stops? In second  case  try  to change  pin  code from alarm  panel... let me know

**Comment by karlismaj** [comment]
Hello. I’ve just set up it and launched. It has never worked so far. Maybe because I’m noob in HA and Mqtt. PIN is right but I think I did not made right HA configuration file so I would appreciate if you could help me with this by sending some examples of code that I need to put into configuration file.

On 13 Sep 2020, at 02:02, Luca Calcaterra <notifications@github.com> wrote:

﻿

Never worked before or before worked and now stops? In second case try to change pin code from alarm panel... let me know

**Comment by pergolafabio** [comment]
If it's to difficult to setup, wait untill Thursday in next release 115, then it's a official integration...

No need anymore for a seperate docker or mqtt

**Comment by karlismaj** [comment]
You mean it will be available as an home assistant official integration like these? https://www.home-assistant.io/integrations/#alarm
Or it will be part of HACS? 
Thursday, you mean 17th of September?
Will app.js still be require to be launched?

**Comment by pergolafabio** [comment]
Yes, official, no hacs, and yes, this Thursday when beta is over... You can already install beta if you want

**Comment by pergolafabio** [comment]
https://rc--home-assistant-docs.netlify.app/integrations/risco/

**Comment by karlismaj** [comment]
Hello

I see that Risco is now officially released. I’ve installed it, added account and and pin. Connection was successful, but I cannot add alarm card because entity for risco is not found.

There is no drop down for risco in entity list

Many thanks

**Comment by pergolafabio** [comment]
no idea, working fine here :), also updated

**Comment by karlismaj** [comment]
Do you use standard alarm panel card?
Can you send me a code from the card? Maybe i can manually add it. I’ve now installed risco on 3 different HA installations including a fresh one without and no luck.

**Comment by pergolafabio** [comment]
Yeah, just default lovelace card, no code

**Comment by karlismaj** [comment]
Sorry for asking so much questions, but do you have wifi connected system? I have GSM based, maybe this is the problem as HA cannot find wifi device on my network.

**Comment by pergolafabio** [comment]
You need riscocloud indeed

**Comment by karlismaj** [comment]
I do have. I use iRISCO mobile app. I was able to connect HA to my Rus iCloud account. It recognized all my zones. But I don’t see entity in the list so I could not add it to alarm card. What is the code for that? Maybe I could just write it manually...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pergolafabio** [comment]
No idea, no coded needed, there must be an entity created the same like the other sensors and binary sensors

**Comment by pergolafabio** [comment]
Can you make some screenshots from the entities created in the risco integration? Do you only see binary sensors there? Also is there an error in your log file?

But discuss here please : 

https://community.home-assistant.io/t/risco-lightsys-alarm-component/82359/156

It has nothing to do with this docker anyway

**Comment by lucacalcaterra** [comment]
#close for inactivity
