### ISSUE TITLE
I need you feedbacks !

### ISSUE THREAD

**Issue by lucacalcaterra** [lucacalcaterra/risco-mqtt-bridge#37]
Hi, 

i'm quite finished  new version of this bridge using updated API (Thanks to @mancioshell ) 
But before to finish and publish i would like to know how many users still use it, since H.A. has now his own binding.

How many users use it for openhab or other domotics controller ? If prevalence is on openhab, is convenient to develop a native binding abandoning this project.

Thanks for you feedback.

Luca

**Comment by pergolafabio** [comment]
It's quite popular on HA community forums about official HA version, so don't think any HA users are using this docker anymore

**Comment by pbda** [comment]
I use it with Domoticz thru MQTT. I don't use alarm status because I already have it with an hardware feedback. I use it only to arm/disarm Risco alarm.

**Comment by yuvalmesika** [comment]
Hi Luca,
Can you share the new integration (with the updated API)
I'm using your project and not the HA risco integration (I have the RiscoCommpact panel and it does not work with the new integration).

**Comment by mrbarbz** [comment]
I have stopped using this version since it was added to HA via integration. But I'm getting random drop outs. I'm going to set your one back up and see if no drop outs

**Comment by lucacalcaterra** [comment]
> I have stopped using this version since it was added to HA via integration. But I'm getting random drop outs. I'm going to set your one back up and see if no drop outs

Drop out probably are caused by polling frequency...

**Comment by claudiosala80** [comment]
I read this post now... I am still using your bridge since I don't like how the home assistant integration works (or maybe I don't understand how configure it!)
I have two partitions and the home assistant integration create two panel. So at the moment I prefer your implementation

**Comment by orenkandel** [comment]
I'm interested in connecting my OH3 with Risco Cloud. Any news regarding the availability of an OH Binding coming up?
