### ISSUE TITLE
Application Hang With pm2

### ISSUE THREAD

**Issue by beckynet** [lucacalcaterra/risco-mqtt-bridge#4]
Hello world,

I've installed this app in /opt/risco-mqtt-bridge.
When I launch it manually with node app.js it seem to run fine.

20-11-2018 09:18:45 debug: Class Connection Constructor end
20-11-2018 09:18:45 info: Connected to MQTT Server
20-11-2018 09:18:46 debug: Logged...Response code is 302: OK
20-11-2018 09:18:46 debug: ...site and Pin Code sent...Response code is 302: OK
20-11-2018 09:18:47 debug: ...Cameras taken...Response code is 200 and no data error: OK
20-11-2018 09:18:47 debug: ...Event History taken...Response code is 200 and no data error: OK
20-11-2018 09:18:48 debug: ...Detectors taken...Response code is 200 and no data error: OK
20-11-2018 09:18:48 debug: ...Overview taken...Response code is 200 and no data error: OK
20-11-2018 09:18:48 debug: return null, overview empty!
20-11-2018 09:18:48 debug: newarmstatus emitted
20-11-2018 09:18:48 info: Arming status: disarmed
20-11-2018 09:18:48 info: publish messages on MQTT Server
20-11-2018 09:18:48 debug: Init function for getting data from Cloud completed: OK
20-11-2018 09:18:48 debug: polling started...
20-11-2018 09:18:58 debug: polling ...
20-11-2018 09:18:59 debug: return null, overview empty!
20-11-2018 09:18:59 debug: Polled...counter:  0
20-11-2018 09:19:09 debug: polling ...
20-11-2018 09:19:10 debug: return null, overview empty!
20-11-2018 09:19:10 debug: Polled...counter:  1
...

But when I try to automatise it with pm2 with this launch file.

risco.yml
apps:
  - script   : app.js
    watch  : true

app hang and restart continuously

20-11-2018 09:20:00 info: Connected to MQTT Server
20-11-2018 09:20:00 info: Exiting ...
20-11-2018 09:20:00 info: Connected to MQTT Server
20-11-2018 09:20:00 info: Exiting ...
20-11-2018 09:20:00 info: Connected to MQTT Server
20-11-2018 09:20:00 info: Exiting ...
20-11-2018 09:20:01 info: Connected to MQTT Server
20-11-2018 09:20:01 info: Exiting ...
20-11-2018 09:20:01 info: Connected to MQTT Server
20-11-2018 09:20:01 info: Exiting ...
....

App name │ id │ version │ mode │ pid │ status   │ restart │ uptime │ cpu │ mem    │ user │ watching │
  │ app      │ 0  │ 1.1.2   │ fork │ 0   │ stopping │ 1740    │ 0      │ 0%  │ 0 B    │ root │ enabled  │

what did I do wrong ?

Thanks for your help

**Comment by lucacalcaterra** [comment]
Which PM2 version you have ?

and... why do you use .yml ? No needed for it..  even watch mode not needed.

Simply install latest version of pm2 with npm i -g pm2 , then  launch pm2 start app.js  . 

Check then with pm2 if running..

I've not problem in this way.

Let me know

**Comment by beckynet** [comment]
Here is my risco.yml

apps:
  - script   : /opt/risco-mqtt-bridge/app.js
    env    :
      NODE_ENV: development

I've started the app at 05:52 with pm2 start risco.yml and log stop at 12:42 but the apps.js seem to always work in pm2. (look pm2.result.txt)

![htop](https://user-images.githubusercontent.com/2901809/48957140-206ce200-ef57-11e8-8325-c7456ce40db0.jpg)

[combined.log](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2611487/combined.log)
[debug.log](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2611488/debug.log)
[pm2.result.txt](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2611490/pm2.result.txt)
[risco.yml.txt](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2611492/risco.yml.txt)

**Comment by lucacalcaterra** [comment]
Still problems or can close it ?

**Comment by beckynet** [comment]
Still problem, I must use cron to have relative success
mp2 restart 0 every hour

Le mer. 2 janv. 2019 à 09:56, Luca Calcaterra <notifications@github.com> a
écrit :

**Comment by lucacalcaterra** [comment]
My pm2 app works from two month...  try with  docker  container and let me know,...

**Comment by beckynet** [comment]
I don't know docker.
I've installed docker-ce but what must I do after ?

Le lun. 21 janv. 2019 à 12:17, Luca Calcaterra <notifications@github.com> a
écrit :

**Comment by lucacalcaterra** [comment]
I must update the README... wait a little :-)
