### ISSUE TITLE
SiteID Risco Local Installer

### ISSUE THREAD

**Issue by Toniadiell** [lucacalcaterra/risco-mqtt-bridge#44]
Hey! Thank you very much for all your work with de binding with Risco. I'm trying to use it with this local installer that uses de Risco Cloud but I cannot get de Installer ID. The acces page is this: https://alarma.planafabrega.com/ELAS/WebUI. What can I do? Thanks!! @lucacalcaterra

**Comment by lucacalcaterra** [comment]
@Toniadiell probably too late :-( sorry... feel to reopen issue
