### ISSUE TITLE
Can't Arm the alarm, disarm works

### ISSUE THREAD

**Issue by zamzon** [lucacalcaterra/risco-mqtt-bridge#5]
[combined.log](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2601022/combined.log)
[error.log](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2601024/error.log)

[config.js.txt](https://github.com/lucacalcaterra/risco-mqtt-bridge/files/2601028/config.js.txt)

I can't arm the system from MQTT, but disarm works.

**Comment by lucacalcaterra** [comment]
you solved ? If not, let me know which panel do you have and no. of partitions.

**Comment by zamzon** [comment]
Hi 
I haven’t used it since, so I don’t know if it’s working now.
Do a need to update something to test if it’s working?
I’m using a Iconnect G2 alarm with MyELAS
I have one partition.

**Comment by lucacalcaterra** [comment]
Pull the latest commit of the repo, even there are not any major changes .

Have you tried to change in config www.riscocloud.com to www.myelas.com ? In the error log there are some error 500 ... sure your username , password code and SelectSiteId are right ?

**Comment by zamzon** [comment]
Hi

I did try to download the newest version with this code:
git clone https://github.com/lucacalcaterra/risco-mqtt-bridge.git

it does look like it connects to the myelas and the mqtt broker. but nothing is send to the broker. if i send a armed to topic "riscopanel/armstatus/SET" i can see in the log it has received the command and it react on the arm/disarm code, but nothing happens on the alarm.

If I arm the alarm from the Riscocloud website i can see in the log it receives the arm code, but nothing is send out to the MQTT broker.

here is my log:

19-03-2019 23:10:06 ^[[32minfo^[[39m: Connected to MQTT Server
19-03-2019 23:14:15 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:14:28 ^[[32minfo^[[39m: message from mqtt arrived:riscopanel/armstatus/SET/armed
19-03-2019 23:14:28 ^[[32minfo^[[39m: arm/disarm command arrived
19-03-2019 23:15:49 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:16:30 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:16:40 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:17:35 ^[[32minfo^[[39m: Exiting ...
19-03-2019 23:25:21 ^[[32minfo^[[39m: Connected to MQTT Server
19-03-2019 23:26:00 ^[[32minfo^[[39m: message from mqtt arrived:riscopanel/armstatus/SET/armed
19-03-2019 23:26:00 ^[[32minfo^[[39m: arm/disarm command arrived
19-03-2019 23:26:36 ^[[32minfo^[[39m: message from mqtt arrived:riscopanel/armstatus/SET/armedll
19-03-2019 23:26:36 ^[[32minfo^[[39m: arm/disarm command arrived
19-03-2019 23:26:36 ^[[33mwarn^[[39m: arm command not recognized
19-03-2019 23:26:50 ^[[32minfo^[[39m: message from mqtt arrived:riscopanel/armstatus/SET/disarmed
19-03-2019 23:26:50 ^[[32minfo^[[39m: arm/disarm command arrived
19-03-2019 23:26:55 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:27:06 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:27:36 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:28:38 ^[[32minfo^[[39m: Status panel infos arrived
19-03-2019 23:29:56 ^[[32minfo^[[39m: Exiting ...

**Comment by lucacalcaterra** [comment]
have solved it ?
