### ISSUE TITLE
Problem during arm 

### ISSUE THREAD

**Issue by 03397** [lucacalcaterra/risco-mqtt-bridge#53]
Hey Luca.
An error pops up when I am arming my alarm. See below
The alarm at the end is armed. Copying the messages before and after the arming.
For your information this is being used in a docker  container and the image used is the latest from docker hub.

16-05-2023 08:32:02 info: Arming status: armed
16-05-2023 08:32:02 info: publish messages on MQTT Server
16-05-2023 08:32:02 info: Status panel infos arrived
16-05-2023 08:32:12 debug: polling ...
16-05-2023 08:32:13 debug: ...Control Panel State taken and overview not empty... OK
16-05-2023 08:32:13 debug: Polled...counter:  3004
16-05-2023 08:32:13 debug: newarmstatus emitted
16-05-2023 08:32:13 info: Arming status: armed
16-05-2023 08:32:13 info: Status panel infos arrived
/app/app.js:59
      const detectorsArray = riscoPoller.riscoConn.riscoDetectors.parts[0].detectors;
                                                                  ^
TypeError: Cannot read properties of null (reading 'parts')
    at RiscoPoller.<anonymous> (/app/app.js:59:67)
    at RiscoPoller.emit (node:events:513:28)
    at Timeout._onTimeout (/app/panelPoller.js:53:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.12.1
16-05-2023 08:32:22 debug: Class Connection Constructor end
16-05-2023 08:32:22 info: Express server started...
16-05-2023 08:32:22 info: Connected to MQTT Server
16-05-2023 08:32:23 debug: Logged...Response code is 302: OK

**Comment by 03397** [comment]
More logs during disarm

16-05-2023 15:41:13 debug: polling ...
16-05-2023 15:41:13 debug: ...Control Panel State taken and overview not empty... OK
16-05-2023 15:41:13 debug: Polled...counter:  9
16-05-2023 15:41:13 debug: newarmstatus emitted
16-05-2023 15:41:13 info: Arming status: disarmed
16-05-2023 15:41:13 info: Status panel infos arrived
/app/app.js:59
      const detectorsArray = riscoPoller.riscoConn.riscoDetectors.parts[0].detectors;
                                                                  ^
TypeError: Cannot read properties of null (reading 'parts')
    at RiscoPoller.<anonymous> (/app/app.js:59:67)
    at RiscoPoller.emit (node:events:513:28)
    at Timeout._onTimeout (/app/panelPoller.js:53:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.12.1
16-05-2023 15:41:17 debug: Class Connection Constructor end
16-05-2023 15:41:17 info: Express server started...

**Comment by lucacalcaterra** [comment]
Hi @03397 , ati this time have not time to follow the issues... could be possible a breakdown during latest risco update ?

**Comment by 03397** [comment]
I don't know if this will help you but during that I have a similar code  and I am getting this
Error fetching risco data: {'result': 72, 'validationErrors':
None, 'errorText': None, 'errorTextCodeID': None, 'status': 200, 'response': None}

This is an empty response which can be correlated with the node.js error you see above.  I think in your code you do not handle the empty response. This is happening forerer and not because of Risco's upgrade , and this is Risco's think not yours.
