### ISSUE TITLE
Question: cameras

### ISSUE THREAD

**Issue by pergolafabio** [lucacalcaterra/risco-mqtt-bridge#9]
ok, this is really interesting, is it also possible to get the camera feed of the onvif/generic cameras in the risco cloud system ?

**Comment by lucacalcaterra** [comment]
I'm working on it... Probably in next release.
Luca

**Comment by pergolafabio** [comment]
really nice!
will this become available as ad addon in Home Assistant?

**Comment by lucacalcaterra** [comment]
Who knows ?! :-) I've no experience on H.A. addons development.. if I have time I'll do it...

@pergolafabio  (sei italiano ? Puoi scrivermi all'indirizzo calcaterra.luca@gmail.com)

**Comment by pergolafabio** [comment]
ok, really nice, already thinking of placing NFC tags on my front door, so i can control the risco alarm with a smart watch or android phone :)
